-- Matterport seed — generated from 'MATTERPORT UPDATE - 13 des 25.xlsx'
-- Wipe & replace catalog properties.
-- Run AFTER supabase/schema.sql. Objects live in schema `homespot`.
BEGIN;
SET search_path = homespot, public;
DELETE FROM applications;  -- FK cleanup
DELETE FROM ai_scores;
DELETE FROM property_tours;
DELETE FROM properties;

INSERT INTO properties (slug, title, developer, city, province, address, bedrooms, bathrooms, land_m2, building_m2, price_idr, vr_tour_url, hero_image_url, status, property_type, category, description, features, rating, tier) VALUES
  ('pik2-garnet-8-x-15', 'Garnet 8 x 15', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 3, 2, 120.0, 84, 3000000000, 'https://my.matterport.com/show/?m=EYZdKHTVvCu', NULL, 'available', 'rumah_tapak', 'premium', 'Garnet 8 x 15 — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('pik2-jati-8-x-20', 'Jati 8 x 20', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 3, 2, 160.0, 112, 4000000000, 'https://my.matterport.com/show/?m=MdByJAdPPPM', NULL, 'available', 'rumah_tapak', 'premium', 'Jati 8 x 20 — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('pik2-kuningan-village-marble', 'Kuningan Village - Marble', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 3, 2, 100.0, 70, 2500000000, 'https://my.matterport.com/show/?m=t5pgrb7FcQM', NULL, 'available', 'rumah_tapak', 'premium', 'Kuningan Village - Marble — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('pik2-mahogani-8-x-12-5', 'Mahogani 8 X 12,5', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 3, 2, 100.0, 70, 2500000000, 'https://my.matterport.com/show/?m=pd7N4KJNq5K', NULL, 'available', 'rumah_tapak', 'premium', 'Mahogani 8 X 12,5 — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('pik2-eboni-10-x-15', 'Eboni 10 X 15', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 3, 2, 150.0, 105, 3750000000, 'https://my.matterport.com/show/?m=K8u9dKMDxPX', NULL, 'available', 'rumah_tapak', 'premium', 'Eboni 10 X 15 — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('pik2-hana-6-x-10', 'Hana 6 X 10', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 2, 1, 60.0, 42, 1500000000, 'https://my.matterport.com/show/?m=49YhCMTK5Az', NULL, 'available', 'rumah_tapak', 'premium', 'Hana 6 X 10 — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('pik2-brown-4-5-x-10', 'Brown 4,5 X 10', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 2, 1, 45.0, 31, 1125000000, 'https://my.matterport.com/show/?m=Ld7sixzzRN3', NULL, 'available', 'rumah_tapak', 'premium', 'Brown 4,5 X 10 — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 3'),
  ('pik2-ivory-6-x-10', 'Ivory 6 X 10', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 2, 1, 60.0, 42, 1500000000, 'https://my.matterport.com/show/?m=RuPEsQdx89e', NULL, 'available', 'rumah_tapak', 'premium', 'Ivory 6 X 10 — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('pik2-olive-8-x-10', 'Olive 8 x 10', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 2, 1, 80.0, 56, 2000000000, 'https://my.matterport.com/show/?m=JcYxcFik1E5', NULL, 'available', 'rumah_tapak', 'premium', 'Olive 8 x 10 — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('pik2-burgundy-4-5-x-12-5', 'Burgundy 4,5 X 12,5', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 2, 1, 56.25, 39, 1406250000, 'https://my.matterport.com/show/?m=4QVXown2qWP', NULL, 'available', 'rumah_tapak', 'premium', 'Burgundy 4,5 X 12,5 — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 3'),
  ('pik2-clover-6x10', 'Clover 6x10', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 2, 1, 60.0, 42, 1500000000, 'https://my.matterport.com/show/?m=jFydbyDHUWE', NULL, 'available', 'rumah_tapak', 'premium', 'Clover 6x10 — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('pik2-hazel-4-5x10-3-lantai', 'Hazel 4,5x10 3 lantai', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 2, 1, 45.0, 31, 1125000000, 'https://my.matterport.com/show/?m=cvVkEaMHib5', NULL, 'available', 'rumah_tapak', 'premium', 'Hazel 4,5x10 3 lantai — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 3'),
  ('pik2-fuschia-6x12-5', 'Fuschia 6x12,5', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 2, 1, 75.0, 52, 1875000000, 'https://my.matterport.com/show/?m=FYaSL13Zu67', NULL, 'available', 'rumah_tapak', 'premium', 'Fuschia 6x12,5 — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('pik2-dahlia', 'Dahlia', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 3, 2, 100.0, 70, 2500000000, 'https://my.matterport.com/show/?m=PrikMJiqSsY', NULL, 'available', 'rumah_tapak', 'premium', 'Dahlia — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('pik2-legian-10x20m', 'Legian 10x20m', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 4, 3, 200.0, 140, 5000000000, 'https://my.matterport.com/show/?m=newT9L8Kp8U', NULL, 'available', 'rumah_tapak', 'premium', 'Legian 10x20m — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 1'),
  ('pik2-kuta-10x30m', 'Kuta 10x30m', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 4, 3, 300.0, 210, 7500000000, 'https://my.matterport.com/show/?m=xuAUJPtXzuW', NULL, 'available', 'rumah_tapak', 'luxury', 'Kuta 10x30m — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 1'),
  ('pik2-bizpark-pik2-9x30m', 'Bizpark PIK2 9x30m', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 4, 3, 270.0, 189, 6750000000, 'https://my.matterport.com/show/?m=MrorQAnwhVf', NULL, 'available', 'rumah_tapak', 'luxury', 'Bizpark PIK2 9x30m — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 1'),
  ('pik2-bizpark-pik2-6x20m', 'Bizpark PIK2 6x20m', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 3, 2, 120.0, 84, 3000000000, 'https://my.matterport.com/show/?m=gWb5YVuqVnc', NULL, 'available', 'rumah_tapak', 'premium', 'Bizpark PIK2 6x20m — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('pik2-himawari-johar-8x10', 'Himawari / Johar 8x10', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 2, 1, 80.0, 56, 2000000000, 'https://my.matterport.com/models/13ypHMRamaT', NULL, 'available', 'rumah_tapak', 'premium', 'Himawari / Johar 8x10 — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('pik2-yuri-camar-4-5-x-10', 'Yuri / Camar 4,5 x 10', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 2, 1, 45.0, 31, 1125000000, 'https://my.matterport.com/models/haM78LsoGy3', NULL, 'available', 'rumah_tapak', 'premium', 'Yuri / Camar 4,5 x 10 — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 3'),
  ('pik2-cendana-10-x-20', 'Cendana 10 x 20', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 4, 3, 200.0, 140, 5000000000, 'https://my.matterport.com/models/z7ykAypgAoe', NULL, 'available', 'rumah_tapak', 'premium', 'Cendana 10 x 20 — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 1'),
  ('pik2-lavender-5-x-15', 'Lavender 5 x 15', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 2, 1, 75.0, 52, 1875000000, 'https://my.matterport.com/show/?m=czA6EiqeKaM', NULL, 'available', 'rumah_tapak', 'premium', 'Lavender 5 x 15 — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('pik2-dormintory', 'Dormintory', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 3, 2, 100.0, 70, 2500000000, 'https://my.matterport.com/show/?m=X9QKjLEdaV5', NULL, 'available', 'rumah_tapak', 'premium', 'Dormintory — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('pik2-marlen-6-x-10-pasadena-spring', 'Marlen 6 x 10 - Pasadena Spring', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 2, 1, 60.0, 42, 1500000000, 'https://my.matterport.com/show/?m=FBu5GXnb4E2', NULL, 'available', 'rumah_tapak', 'premium', 'Marlen 6 x 10 - Pasadena Spring — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('pik2-kayla-6-x-9-ilona', 'Kayla 6 x 9 - Ilona', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 2, 1, 54.0, 38, 1350000000, 'https://my.matterport.com/show/?m=aHpG3TTtiGZ', NULL, 'available', 'rumah_tapak', 'premium', 'Kayla 6 x 9 - Ilona — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 3'),
  ('pik2-ilona-kalista-4-5-x-9', 'ILONA - Kalista 4,5 X 9', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 2, 1, 40.5, 28, 1012500000, 'https://my.matterport.com/show/?m=ht2sBMJSyLi', NULL, 'available', 'rumah_tapak', 'premium', 'ILONA - Kalista 4,5 X 9 — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 3'),
  ('pik2-kirana-4-5-x-9', 'Kirana 4,5 x 9', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 2, 1, 40.5, 28, 1012500000, 'https://my.matterport.com/show/?m=jLRdcMDXfsj', NULL, 'available', 'rumah_tapak', 'premium', 'Kirana 4,5 x 9 — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 3'),
  ('pik2-dormintory-4-5-x-8-5', 'Dormintory 4,5 X 8,5', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 2, 1, 38.25, 27, 956250000, 'https://my.matterport.com/show/?m=jxK91VAks4Z', NULL, 'available', 'rumah_tapak', 'premium', 'Dormintory 4,5 X 8,5 — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 3'),
  ('pik2-florida-hoek-grey-9-x-10-m', 'Florida Hoek Grey 9 X 10 M', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 2, 1, 90.0, 63, 2250000000, 'https://my.matterport.com/show/?m=zxGvnvVj4we', NULL, 'available', 'rumah_tapak', 'premium', 'Florida Hoek Grey 9 X 10 M — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('pik2-casa-montana-alpha-3-5x9m-pik2', 'Casa Montana-Alpha 3,5x9m PIK2', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 2, 1, 31.5, 22, 787500000, 'https://my.matterport.com/show/?m=dDNvefpJcM9', NULL, 'available', 'rumah_tapak', 'premium', 'Casa Montana-Alpha 3,5x9m PIK2 — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 3'),
  ('pik2-casa-montana-beta-3-5x9-pik2', 'casa montana - Beta 3,5x9 Pik2', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 2, 1, 31.5, 22, 787500000, 'https://my.matterport.com/show/?m=5t8yjH8yePM', NULL, 'available', 'rumah_tapak', 'premium', 'casa montana - Beta 3,5x9 Pik2 — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 3'),
  ('pik2-casa-montana-omega-5x9m-pik2', 'casa montana-omega 5x9m pik2', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'PIK2, Jakarta Utara', 2, 1, 45.0, 31, 1125000000, 'https://my.matterport.com/show/?m=EEmHMCUmpZ1', NULL, 'available', 'rumah_tapak', 'premium', 'casa montana-omega 5x9m pik2 — bagian dari proyek PIK2 oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 3'),
  ('golf-island-huzel', 'Huzel', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'GOLF ISLAND, Jakarta Utara', 3, 2, 100.0, 70, 3000000000, 'https://my.matterport.com/show/?m=M6dx2bfcxv8', NULL, 'available', 'rumah_tapak', 'luxury', 'Huzel — bagian dari proyek GOLF ISLAND oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('golf-island-violin-palm-8x25m', 'Violin - Palm 8x25M', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'GOLF ISLAND, Jakarta Utara', 4, 3, 200.0, 140, 6000000000, 'https://my.matterport.com/show/?m=dhYnsDZAC1U', NULL, 'available', 'rumah_tapak', 'luxury', 'Violin - Palm 8x25M — bagian dari proyek GOLF ISLAND oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 1'),
  ('golf-island-harmony-pine-8x20m-ff', 'Harmony - Pine 8x20m FF', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'GOLF ISLAND, Jakarta Utara', 3, 2, 160.0, 112, 4800000000, 'https://my.matterport.com/show/?m=Lv2qJaVxgbx', NULL, 'available', 'rumah_tapak', 'luxury', 'Harmony - Pine 8x20m FF — bagian dari proyek GOLF ISLAND oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('golf-island-simphony-fully-furnished', 'Simphony Fully Furnished', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'GOLF ISLAND, Jakarta Utara', 3, 2, 100.0, 70, 3000000000, 'https://my.matterport.com/show/?m=7AQeCzjvUQK', NULL, 'available', 'rumah_tapak', 'luxury', 'Simphony Fully Furnished — bagian dari proyek GOLF ISLAND oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('golf-island-concerto-acacia-10x15m', 'Concerto Acacia 10x15M', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'GOLF ISLAND, Jakarta Utara', 3, 2, 150.0, 105, 4500000000, 'https://my.matterport.com/show/?m=7rGao3zXZ6J', NULL, 'available', 'rumah_tapak', 'luxury', 'Concerto Acacia 10x15M — bagian dari proyek GOLF ISLAND oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('golf-island-papyrus', 'Papyrus', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'GOLF ISLAND, Jakarta Utara', 3, 2, 100.0, 70, 3000000000, 'https://my.matterport.com/show/?m=BMfB1rzteKh', NULL, 'available', 'rumah_tapak', 'luxury', 'Papyrus — bagian dari proyek GOLF ISLAND oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('golf-island-harmony-pine-8x20', 'Harmony - Pine 8x20', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'GOLF ISLAND, Jakarta Utara', 3, 2, 160.0, 112, 4800000000, 'https://my.matterport.com/show/?m=F5pb8bS5RM2', NULL, 'available', 'rumah_tapak', 'luxury', 'Harmony - Pine 8x20 — bagian dari proyek GOLF ISLAND oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('golf-island-violin-type-palm', 'Violin - Type Palm', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'GOLF ISLAND, Jakarta Utara', 3, 2, 100.0, 70, 3000000000, 'https://my.matterport.com/show/?m=cP2JVfihGrw', NULL, 'available', 'rumah_tapak', 'luxury', 'Violin - Type Palm — bagian dari proyek GOLF ISLAND oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('sedayu-city-klp-gading-eropa-florence-6x15m', 'Eropa-Florence 6x15m', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'SEDAYU CITY @KLP GADING, Jakarta Utara', 2, 1, 90.0, 63, 1980000000, 'https://my.matterport.com/show/?m=V7w3DmwyDwm', NULL, 'available', 'rumah_tapak', 'upper_mid', 'Eropa-Florence 6x15m — bagian dari proyek SEDAYU CITY @KLP GADING oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('sedayu-city-klp-gading-eropa-barcelona-6x12-5-m', 'Eropa-Barcelona 6x12,5 M', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'SEDAYU CITY @KLP GADING, Jakarta Utara', 2, 1, 75.0, 52, 1650000000, 'https://my.matterport.com/show/?m=39gVXisK5sD', NULL, 'available', 'rumah_tapak', 'upper_mid', 'Eropa-Barcelona 6x12,5 M — bagian dari proyek SEDAYU CITY @KLP GADING oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('sedayu-city-klp-gading-eropa-london-8x12-5m', 'Eropa - London 8x12,5M', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'SEDAYU CITY @KLP GADING, Jakarta Utara', 3, 2, 100.0, 70, 2200000000, 'https://my.matterport.com/show/?m=gcXkiGjxLLZ', NULL, 'available', 'rumah_tapak', 'upper_mid', 'Eropa - London 8x12,5M — bagian dari proyek SEDAYU CITY @KLP GADING oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('sedayu-city-klp-gading-summerwood-jasmine-8x15', 'Summerwood - Jasmine 8x15', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'SEDAYU CITY @KLP GADING, Jakarta Utara', 3, 2, 120.0, 84, 2640000000, 'https://my.matterport.com/show/?m=CL8gA8yw1cv', NULL, 'available', 'rumah_tapak', 'upper_mid', 'Summerwood - Jasmine 8x15 — bagian dari proyek SEDAYU CITY @KLP GADING oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('sedayu-city-klp-gading-summerwood-aster-4-5x10', 'Summerwood - Aster 4.5x10', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'SEDAYU CITY @KLP GADING, Jakarta Utara', 2, 1, 45.0, 31, 990000000, 'https://my.matterport.com/show/?m=VgYvGU7eSMi', NULL, 'available', 'rumah_tapak', 'upper_mid', 'Summerwood - Aster 4.5x10 — bagian dari proyek SEDAYU CITY @KLP GADING oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 3'),
  ('sedayu-city-klp-gading-springwood-damar-8x25', 'Springwood - Damar 8x25', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'SEDAYU CITY @KLP GADING, Jakarta Utara', 4, 3, 200.0, 140, 4400000000, 'https://my.matterport.com/show/?m=NX5sur8adwE', NULL, 'available', 'rumah_tapak', 'upper_mid', 'Springwood - Damar 8x25 — bagian dari proyek SEDAYU CITY @KLP GADING oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('sedayu-city-klp-gading-summerwood-lavender-10x15', 'Summerwood - Lavender 10x15', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'SEDAYU CITY @KLP GADING, Jakarta Utara', 3, 2, 150.0, 105, 3300000000, 'https://my.matterport.com/show/?m=xG7qDpoBHsw', NULL, 'available', 'rumah_tapak', 'upper_mid', 'Summerwood - Lavender 10x15 — bagian dari proyek SEDAYU CITY @KLP GADING oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('sedayu-city-klp-gading-springwood-cendana-10x25', 'Springwood - Cendana 10x25', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'SEDAYU CITY @KLP GADING, Jakarta Utara', 4, 3, 250.0, 175, 5500000000, 'https://my.matterport.com/show/?m=BFUDiru2VH4', NULL, 'available', 'rumah_tapak', 'luxury', 'Springwood - Cendana 10x25 — bagian dari proyek SEDAYU CITY @KLP GADING oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 1'),
  ('sedayu-city-klp-gading-springwood-damar-8x25-48', 'SPRINGWOOD DAMAR 8X25', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'SEDAYU CITY @KLP GADING, Jakarta Utara', 4, 3, 200.0, 140, 4400000000, 'https://my.matterport.com/show/?m=sk7SHPPettR', NULL, 'available', 'rumah_tapak', 'upper_mid', 'SPRINGWOOD DAMAR 8X25 — bagian dari proyek SEDAYU CITY @KLP GADING oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('gold-coast-aparment-caribbean-2-br', 'Caribbean 2 BR', 'Agung Sedayu Group', 'Jakarta Utara', 'DKI Jakarta', 'GOLD COAST APARMENT, Jakarta Utara', 2, 1, 0, 60.0, 3000000000, 'https://my.matterport.com/show/?m=y6Xe5FxBE7s', NULL, 'available', 'apartemen', 'premium', 'Caribbean 2 BR — bagian dari proyek GOLD COAST APARMENT oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('fatmawati-city-center-apartment-corona-tower-2-br-55-sqm', 'Corona Tower - 2 BR - 55 sqm', 'Agung Sedayu Group', 'Jakarta Selatan', 'DKI Jakarta', 'FATMAWATI CITY CENTER APARTMENT, Jakarta Selatan', 2, 1, 0, 55.0, 2475000000, 'https://my.matterport.com/show/?m=9Zs5X4NvcbM', NULL, 'available', 'apartemen', 'upper_mid', 'Corona Tower - 2 BR - 55 sqm — bagian dari proyek FATMAWATI CITY CENTER APARTMENT oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('fatmawati-city-center-apartment-victoria-tower-2-br-61-sqm', 'Victoria Tower - 2 BR - 61 sqm', 'Agung Sedayu Group', 'Jakarta Selatan', 'DKI Jakarta', 'FATMAWATI CITY CENTER APARTMENT, Jakarta Selatan', 2, 1, 0, 61.0, 2745000000, 'https://my.matterport.com/show/?m=Z7vtJ6pv79Y', NULL, 'available', 'apartemen', 'upper_mid', 'Victoria Tower - 2 BR - 61 sqm — bagian dari proyek FATMAWATI CITY CENTER APARTMENT oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2'),
  ('fatmawati-city-center-apartment-corona-tower-1-br-41-sqm', 'Corona Tower - 1 BR - 41 sqm', 'Agung Sedayu Group', 'Jakarta Selatan', 'DKI Jakarta', 'FATMAWATI CITY CENTER APARTMENT, Jakarta Selatan', 1, 1, 0, 41.0, 1845000000, 'https://my.matterport.com/show/?m=x6xfj2Xq78b', NULL, 'available', 'apartemen', 'upper_mid', 'Corona Tower - 1 BR - 41 sqm — bagian dari proyek FATMAWATI CITY CENTER APARTMENT oleh Agung Sedayu Group. Tour 3D Matterport tersedia.', ARRAY['Tour 3D Matterport','Pre-approval Kilat','Konsultasi KPR'], 4.6, 'Tier 2');

COMMIT;